graph TD;
  callAzureJay("Chama função de consulta") --> resolveJSONSchemas
  resolveJSONSchemas["Monta esquema GraphQL"] --> forgeData
  forgeData["Forja grafo de dados"] --> findRoute
  findRoute["Processa rota para busca do grafo"] --> fetchData
  fetchData["Executa requisições"] --> isEnvDevelopment
  isEnvDevelopment{"É ambiente<br>dev?"} --> |Sim| mergeData
  mergeData("Faz merge<br>com os dados<br>forjados") --> resolveData
  isEnvDevelopment --> |Não| resolveData
  resolveData("Retorna dados")
